id: P007972
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:52:34.292508
source_metadata:
  id: bdr:W4CZ16922
  title: གསོ་རིག་སྨན་གྱི་ཁོག་འབུགས།
  author: ''
  volumes:
    0d22c9149a3c4be59afaac6082a19d16:
      image_group_id: I1KG13567
      title: Volume 1 of gso rig sman gyi khog 'bugs/
      volume_number: 1
      total_pages: 586
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
