id: P007972
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ16922
  title: གསོ་རིག་སྨན་གྱི་ཁོག་འབུགས།
  author: ''
  volumes:
    ca104ca6ec134fc9b207c93ba3fd3d57:
      image_group_id: I1KG13567
      title: ''
      volume_number: 1
      total_pages: 586
ebook_metadata:
  title: གསོ་རིག་སྨན་གྱི་ཁོག་འབུགས།
  author: ''
  sku: P007972
  cover: cover.jpg
  layers:
  - pagination
