id: IC96FFDAC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:05:09+00:00'
last_modified: '2022-06-09T08:10:04.051841+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ16922
  title: གསོ་རིག་སྨན་གྱི་ཁོག་འབུགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9277':
      image_group_id: I1KG13567
      title: Volume 1 of gso rig sman gyi khog 'bugs/
      total_pages: 586
      order: 1
      base_file: 9277.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
